/**
 * hooks/useQueryExecution.ts
 *
 * Manages the full SQL execution lifecycle, separate from
 * conversation state.
 *
 * Conversation state handles:  question → SQL / clarification
 * Execution state handles:     SQL → database results
 *
 * State machine:
 *   idle → loading → success
 *                 → error
 *   (reset returns to idle from any state)
 */

import { useReducer, useCallback, useRef } from "react";
import { executeSQL } from "@/api/execute";

// ============================================================
// Types
// ============================================================

export type ExecutionStatus = "idle" | "loading" | "success" | "error";

export interface ExecutionResult {
  columns: string[];
  rows: unknown[][];
  executionMs: number;
  rowCount: number;
}

export interface QueryExecutionState {
  status: ExecutionStatus;
  result: ExecutionResult | null;
  error: string | null;
  /** The SQL that was last sent to /execute */
  executedSql: string | null;
  /** The SQL currently in the editor (may differ from executedSql) */
  currentSql: string;
  /** True if currentSql !== the SQL that was generated by the AI */
  isEdited: boolean;
}

// ============================================================
// Actions
// ============================================================

type Action =
  | { type: "SET_SQL"; sql: string; generatedSql: string }
  | { type: "EXECUTE_START"; sql: string }
  | { type: "EXECUTE_SUCCESS"; columns: string[]; rows: unknown[][]; executionMs: number }
  | { type: "EXECUTE_ERROR"; message: string }
  | { type: "RESET" };

// ============================================================
// Initial state
// ============================================================

const initialState: QueryExecutionState = {
  status: "idle",
  result: null,
  error: null,
  executedSql: null,
  currentSql: "",
  isEdited: false,
};

// ============================================================
// Reducer
// ============================================================

function reducer(
  state: QueryExecutionState,
  action: Action
): QueryExecutionState {
  switch (action.type) {
    case "SET_SQL": {
      // Called when a new SQL is generated by /ask or /clarify.
      // Resets execution state and seeds the editor.
      return {
        ...initialState,
        currentSql: action.sql,
        isEdited: false,
      };
    }

    case "EXECUTE_START": {
      return {
        ...state,
        status: "loading",
        error: null,
        executedSql: action.sql,
      };
    }

    case "EXECUTE_SUCCESS": {
      return {
        ...state,
        status: "success",
        result: {
          columns: action.columns,
          rows: action.rows,
          executionMs: action.executionMs,
          rowCount: action.rows.length,
        },
        error: null,
      };
    }

    case "EXECUTE_ERROR": {
      return {
        ...state,
        status: "error",
        error: action.message,
        result: null,
      };
    }

    case "RESET": {
      return initialState;
    }

    default:
      return state;
  }
}

// ============================================================
// Hook
// ============================================================

export function useQueryExecution() {
  const [state, dispatch] = useReducer(reducer, initialState);

  // Use a ref for the loading guard so execute() never has a
  // stale closure — it always reads the current value.
  const isLoadingRef = useRef(false);

  // Keep the ref in sync with reducer state
  if (state.status === "loading") {
    isLoadingRef.current = true;
  } else {
    isLoadingRef.current = false;
  }

  /**
   * Called when a new SQL is generated by the AI.
   * Seeds the editor and clears previous results.
   */
  const setGeneratedSql = useCallback(
    (sql: string) => {
      dispatch({ type: "SET_SQL", sql, generatedSql: sql });
    },
    []
  );

  /**
   * Called when the user edits the SQL in the editor.
   * Tracks whether the SQL differs from the generated version.
   */
  const updateCurrentSql = useCallback(
    (sql: string) => {
      // We detect edits by comparing against the last generated SQL
      // stored in state.currentSql at the time SET_SQL was dispatched.
      // Since we want to allow the component to control the textarea
      // value directly, we just update and let the component compare.
      dispatch({
        type: "SET_SQL",
        sql,
        generatedSql: state.executedSql ?? sql,
      });
    },
    [state.executedSql]
  );

  /**
   * Execute the current SQL against the database.
   */
  const execute = useCallback(
    async (sql: string) => {
      const trimmed = sql.trim();
      if (!trimmed || isLoadingRef.current) return;

      dispatch({ type: "EXECUTE_START", sql: trimmed });

      const start = performance.now();
      const result = await executeSQL(trimmed);
      const elapsed = Math.round(performance.now() - start);

      if (!result.ok) {
        const message =
          result.error.status === 400
            ? result.error.message
            : result.error.status === 422
            ? result.error.message
            : result.error.status === 0
            ? "Unable to connect to the server. Please check that the backend is running."
            : "Unable to execute this query. Please check the SQL and try again.";

        dispatch({ type: "EXECUTE_ERROR", message });
        return;
      }

      dispatch({
        type: "EXECUTE_SUCCESS",
        columns: result.data.columns,
        rows: result.data.rows,
        executionMs: elapsed,
      });
    },
    [isLoadingRef]
  );

  /**
   * Reset all execution state (called on new conversation).
   */
  const reset = useCallback(() => {
    dispatch({ type: "RESET" });
  }, []);

  return {
    status: state.status,
    result: state.result,
    error: state.error,
    currentSql: state.currentSql,
    executedSql: state.executedSql,
    isEdited: state.isEdited,
    isLoading: state.status === "loading",
    setGeneratedSql,
    updateCurrentSql,
    execute,
    reset,
  };
}
